// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PQr8FlRNJxuPuz_Tl0sAVHeJB319j4o',
    appId: '1:640447509717:web:1b4a14ac35bebb26599e5c',
    messagingSenderId: '640447509717',
    projectId: 'gameon-mobile',
    authDomain: 'gameon-mobile.firebaseapp.com',
    storageBucket: 'gameon-mobile.firebasestorage.app',
    measurementId: 'G-Y92ZFC7H69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyRkVmA_0xYPY1IGs78Ffbeic14yk7zk',
    appId: '1:640447509717:android:d30da91d1689aa62599e5c',
    messagingSenderId: '640447509717',
    projectId: 'gameon-mobile',
    storageBucket: 'gameon-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdsRPDC2ClKnobGx8DdJd0ksdTKkqpwFA',
    appId: '1:640447509717:ios:d65c45e7bda03f30599e5c',
    messagingSenderId: '640447509717',
    projectId: 'gameon-mobile',
    storageBucket: 'gameon-mobile.firebasestorage.app',
    iosBundleId: 'com.example.gameon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdsRPDC2ClKnobGx8DdJd0ksdTKkqpwFA',
    appId: '1:640447509717:ios:d65c45e7bda03f30599e5c',
    messagingSenderId: '640447509717',
    projectId: 'gameon-mobile',
    storageBucket: 'gameon-mobile.firebasestorage.app',
    iosBundleId: 'com.example.gameon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2PQr8FlRNJxuPuz_Tl0sAVHeJB319j4o',
    appId: '1:640447509717:web:c6477414d7a1dbfd599e5c',
    messagingSenderId: '640447509717',
    projectId: 'gameon-mobile',
    authDomain: 'gameon-mobile.firebaseapp.com',
    storageBucket: 'gameon-mobile.firebasestorage.app',
    measurementId: 'G-1EH22YE682',
  );

}